/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Whether a claim was entered manually or generated by an auto-calculator
 */
export enum ClaimSource {
    MANUAL = 'manual',
    AUTO = 'auto',
}
